name: update-snake
on:
  schedule:
    - cron: "0 0 * * *"
  
  workflow_dispatch:
  
  push:
    branches:
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: generate contribution-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/contribution-snake.svg
            dist/contribution-snake-dark.svg?palette=github-dark
          

      - name: push contribution-snake.svg to the files branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: files
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
